name: meantools
channels:
  - pyg
  - anaconda
  - bioconda
  - rdkit
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - biopython
  - java-jdk
  - libboost
  - libboost-python
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcxx
  - libdeflate
  - libev
  - libexpat
  - libffi
  - libgfortran
  - libgfortran5
  - libglib
  - libhwloc
  - libiconv
  - libjpeg-turbo
  - libpng
  - libprotobuf
  - libsqlite
  - libtiff
  - libuv
  - libwebp-base
  - libxcb
  - libxml2
  - libxslt
  - libzlib
  - llvm-openmp
  - lxml
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - maven
  - networkx
  - numba
  - numpy
  - numpy-base
  - numpydoc
  - openjdk
  - pandas
  - pandoc
  - pandocfilters
  - pip
  - plotly
  - python-dateutil
  - python-fastjsonschema
  - python-libarchive-c
  - python-lsp-black
  - python-lsp-jsonrpc
  - python-lsp-server
  - python-slugify
  - python-snappy
  - python.app
  - python_abi
  - pytoolconfig
  - pyg
  - qt
  - qt-main
  - qt-webengine
  - qtawesome
  - qtconsole
  - qtconsole-base
  - qtpy
  - readline
  - regex
  - scikit-image
  - scikit-learn
  - scikit-learn-intelex
  - scipy
  - scrapy
  - seaborn
  - seaborn-base
  - setuptools
  - sqlite
  - tqdm
  - rdkit
  - pysocks
  - pip:
      - pyzmq
      - arrow
      - kcfconvoy
      - igraph
      - itables
      - jsonpickle
      - keras
      - lazy-loader
      - libclang
      - markdown-it-py
      - markov-clustering
      - matplotlib-venn
      - mdurl
      - multiprocess
      - pandas-flavor
      - peewee
      - pip
      - prody
      - progress
      - progressbar2
      - python-igraph
      - python-utils
      - pyvis
      - rdkit-pypi
      - readme-renderer
      - requests
      - requests-oauthlib
      - requests-toolbelt
      - rfc3986
      - rich
      - simplejson
      - svgelements
      - svgutils
      - taxadb
      - tensorboard
      - tensorboard-data-server
      - tensorboard-plugin-wit
      - tensorflow
      - tensorflow-estimator
      - tensorflow-io-gcs-filesystem
      - termcolor
      - texttable
      - torch
      - torch-geometric
      - torchvision
      - twine
      - typing-extensions
      - urllib3
      - xarray
